"""Initial normalized schema."""
from alembic import op
import sqlalchemy as sa
revision="0001"; down_revision=None
def upgrade():
    op.create_table("users",sa.Column("id",sa.Integer,primary_key=True),sa.Column("name",sa.String(120),nullable=False),sa.Column("email",sa.String(320),nullable=False,unique=True),sa.Column("password_hash",sa.String(255),nullable=False),sa.Column("created_at",sa.DateTime(timezone=True),server_default=sa.func.now()))
    op.create_index("ix_users_email","users",["email"])
    op.create_table("datasets",sa.Column("id",sa.Integer,primary_key=True),sa.Column("user_id",sa.Integer,sa.ForeignKey("users.id",ondelete="CASCADE"),nullable=False),sa.Column("kind",sa.String(20),nullable=False),sa.Column("filename",sa.String(255),nullable=False),sa.Column("content_hash",sa.String(64),nullable=False),sa.Column("created_at",sa.DateTime(timezone=True),server_default=sa.func.now()),sa.UniqueConstraint("user_id","kind","content_hash",name="uq_dataset_content"))
    op.create_index("ix_datasets_owner","datasets",["user_id","kind"])
    op.create_table("orders",sa.Column("id",sa.Integer,primary_key=True),sa.Column("dataset_id",sa.Integer,sa.ForeignKey("datasets.id",ondelete="CASCADE"),nullable=False),sa.Column("order_id",sa.String(120)),sa.Column("order_reference",sa.String(120)),sa.Column("amount",sa.Numeric(18,2),nullable=False),sa.Column("currency",sa.String(3),nullable=False),sa.Column("status",sa.String(40),nullable=False),sa.Column("created_at",sa.DateTime(timezone=True)))
    op.create_index("ix_orders_key","orders",["dataset_id","order_id","order_reference"])
    op.create_table("payments",sa.Column("id",sa.Integer,primary_key=True),sa.Column("dataset_id",sa.Integer,sa.ForeignKey("datasets.id",ondelete="CASCADE"),nullable=False),sa.Column("payment_id",sa.String(120)),sa.Column("order_id",sa.String(120)),sa.Column("order_reference",sa.String(120)),sa.Column("amount",sa.Numeric(18,2),nullable=False),sa.Column("settled_amount",sa.Numeric(18,2)),sa.Column("currency",sa.String(3),nullable=False),sa.Column("status",sa.String(40),nullable=False),sa.Column("created_at",sa.DateTime(timezone=True)))
    op.create_index("ix_payments_key","payments",["dataset_id","order_id","order_reference"])
    op.create_table("reconciliation_results",sa.Column("id",sa.Integer,primary_key=True),sa.Column("user_id",sa.Integer,sa.ForeignKey("users.id",ondelete="CASCADE"),nullable=False),sa.Column("orders_dataset_id",sa.Integer,sa.ForeignKey("datasets.id"),nullable=False),sa.Column("payments_dataset_id",sa.Integer,sa.ForeignKey("datasets.id"),nullable=False),sa.Column("order_id",sa.Integer,sa.ForeignKey("orders.id")),sa.Column("payment_id",sa.Integer,sa.ForeignKey("payments.id")),sa.Column("match_key",sa.String(120),nullable=False),sa.Column("classification",sa.String(40),nullable=False),sa.Column("reason",sa.Text,nullable=False),sa.Column("expected_amount",sa.Numeric(18,2),nullable=False),sa.Column("actual_amount",sa.Numeric(18,2),nullable=False),sa.Column("difference",sa.Numeric(18,2),nullable=False),sa.Column("risk_amount",sa.Numeric(18,2),nullable=False),sa.Column("currency",sa.String(3)),sa.Column("confidence",sa.Numeric(5,4),nullable=False),sa.Column("created_at",sa.DateTime(timezone=True),server_default=sa.func.now()))
    op.create_index("ix_results_owner_class","reconciliation_results",["user_id","classification"])
    op.create_table("llm_explanations",sa.Column("id",sa.Integer,primary_key=True),sa.Column("result_id",sa.Integer,sa.ForeignKey("reconciliation_results.id",ondelete="CASCADE"),unique=True,nullable=False),sa.Column("summary",sa.Text,nullable=False),sa.Column("likely_cause",sa.Text,nullable=False),sa.Column("business_impact",sa.Text,nullable=False),sa.Column("recommended_action",sa.Text,nullable=False),sa.Column("priority",sa.String(20),nullable=False),sa.Column("created_at",sa.DateTime(timezone=True),server_default=sa.func.now()))
def downgrade():
    for table in ("llm_explanations","reconciliation_results","payments","orders","datasets","users"): op.drop_table(table)
