"""add_reconciliation_runs

Revision ID: ae2182ecc0be
Revises: 0001
Create Date: 2026-07-19 23:36:38.351086

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ae2182ecc0be'
down_revision = '0001'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('import_errors',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('dataset_id', sa.Integer(), nullable=False),
    sa.Column('row_index', sa.Integer(), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=False),
    sa.Column('raw_data', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['dataset_id'], ['datasets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('import_errors', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_import_errors_dataset_id'), ['dataset_id'], unique=False)

    op.create_table('reconciliation_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('orders_dataset_id', sa.Integer(), nullable=False),
    sa.Column('payments_dataset_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['orders_dataset_id'], ['datasets.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['payments_dataset_id'], ['datasets.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('reconciliation_runs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_reconciliation_runs_orders_dataset_id'), ['orders_dataset_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_reconciliation_runs_payments_dataset_id'), ['payments_dataset_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_reconciliation_runs_user_id'), ['user_id'], unique=False)

    with op.batch_alter_table('datasets', schema=None) as batch_op:
        batch_op.alter_column('created_at',
               existing_type=sa.DATETIME(),
               nullable=False,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
        batch_op.drop_index('ix_datasets_owner')
        batch_op.create_index(batch_op.f('ix_datasets_user_id'), ['user_id'], unique=False)

    with op.batch_alter_table('llm_explanations', schema=None) as batch_op:
        batch_op.alter_column('created_at',
               existing_type=sa.DATETIME(),
               nullable=False,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))

    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('normalized_order_id', sa.String(length=120), nullable=True))
        batch_op.alter_column('amount',
               existing_type=sa.NUMERIC(precision=18, scale=2),
               type_=sa.Numeric(precision=14, scale=2),
               existing_nullable=False)
        batch_op.drop_index('ix_orders_key')
        batch_op.create_index(batch_op.f('ix_orders_dataset_id'), ['dataset_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_orders_normalized_order_id'), ['normalized_order_id'], unique=False)

    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('normalized_order_reference', sa.String(length=120), nullable=True))
        batch_op.add_column(sa.Column('fee', sa.Numeric(precision=14, scale=2), server_default='0.00', nullable=False))
        batch_op.alter_column('amount',
               existing_type=sa.NUMERIC(precision=18, scale=2),
               type_=sa.Numeric(precision=14, scale=2),
               existing_nullable=False)
        batch_op.alter_column('settled_amount',
               existing_type=sa.NUMERIC(precision=18, scale=2),
               type_=sa.Numeric(precision=14, scale=2),
               existing_nullable=True)
        batch_op.drop_index('ix_payments_key')
        batch_op.create_index(batch_op.f('ix_payments_dataset_id'), ['dataset_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_payments_normalized_order_reference'), ['normalized_order_reference'], unique=False)

    with op.batch_alter_table('reconciliation_results', schema=None) as batch_op:
        batch_op.add_column(sa.Column('run_id', sa.Integer(), nullable=True))
        batch_op.alter_column('expected_amount',
               existing_type=sa.NUMERIC(precision=18, scale=2),
               type_=sa.Numeric(precision=14, scale=2),
               existing_nullable=False)
        batch_op.alter_column('actual_amount',
               existing_type=sa.NUMERIC(precision=18, scale=2),
               type_=sa.Numeric(precision=14, scale=2),
               existing_nullable=False)
        batch_op.alter_column('difference',
               existing_type=sa.NUMERIC(precision=18, scale=2),
               type_=sa.Numeric(precision=14, scale=2),
               existing_nullable=False)
        batch_op.alter_column('risk_amount',
               existing_type=sa.NUMERIC(precision=18, scale=2),
               type_=sa.Numeric(precision=14, scale=2),
               existing_nullable=False)
        batch_op.alter_column('created_at',
               existing_type=sa.DATETIME(),
               nullable=False,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
        batch_op.drop_index('ix_results_owner_class')
        batch_op.create_index(batch_op.f('ix_reconciliation_results_classification'), ['classification'], unique=False)
        batch_op.create_index(batch_op.f('ix_reconciliation_results_run_id'), ['run_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_reconciliation_results_user_id'), ['user_id'], unique=False)
        batch_op.create_foreign_key('fk_results_run_id', 'reconciliation_runs', ['run_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('created_at',
               existing_type=sa.DATETIME(),
               nullable=False,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
        batch_op.drop_index('ix_users_email')
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_email'))
        batch_op.create_index('ix_users_email', ['email'], unique=False)
        batch_op.alter_column('created_at',
               existing_type=sa.DATETIME(),
               nullable=True,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))

    with op.batch_alter_table('reconciliation_results', schema=None) as batch_op:
        batch_op.drop_constraint('fk_results_run_id', type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_reconciliation_results_user_id'))
        batch_op.drop_index(batch_op.f('ix_reconciliation_results_run_id'))
        batch_op.drop_index(batch_op.f('ix_reconciliation_results_classification'))
        batch_op.create_index('ix_results_owner_class', ['user_id', 'classification'], unique=False)
        batch_op.alter_column('created_at',
               existing_type=sa.DATETIME(),
               nullable=True,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
        batch_op.alter_column('risk_amount',
               existing_type=sa.Numeric(precision=14, scale=2),
               type_=sa.NUMERIC(precision=18, scale=2),
               existing_nullable=False)
        batch_op.alter_column('difference',
               existing_type=sa.Numeric(precision=14, scale=2),
               type_=sa.NUMERIC(precision=18, scale=2),
               existing_nullable=False)
        batch_op.alter_column('actual_amount',
               existing_type=sa.Numeric(precision=14, scale=2),
               type_=sa.NUMERIC(precision=18, scale=2),
               existing_nullable=False)
        batch_op.alter_column('expected_amount',
               existing_type=sa.Numeric(precision=14, scale=2),
               type_=sa.NUMERIC(precision=18, scale=2),
               existing_nullable=False)
        batch_op.drop_column('run_id')

    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_payments_normalized_order_reference'))
        batch_op.drop_index(batch_op.f('ix_payments_dataset_id'))
        batch_op.create_index('ix_payments_key', ['dataset_id', 'order_id', 'order_reference'], unique=False)
        batch_op.alter_column('settled_amount',
               existing_type=sa.Numeric(precision=14, scale=2),
               type_=sa.NUMERIC(precision=18, scale=2),
               existing_nullable=True)
        batch_op.alter_column('amount',
               existing_type=sa.Numeric(precision=14, scale=2),
               type_=sa.NUMERIC(precision=18, scale=2),
               existing_nullable=False)
        batch_op.drop_column('fee')
        batch_op.drop_column('normalized_order_reference')

    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_orders_normalized_order_id'))
        batch_op.drop_index(batch_op.f('ix_orders_dataset_id'))
        batch_op.create_index('ix_orders_key', ['dataset_id', 'order_id', 'order_reference'], unique=False)
        batch_op.alter_column('amount',
               existing_type=sa.Numeric(precision=14, scale=2),
               type_=sa.NUMERIC(precision=18, scale=2),
               existing_nullable=False)
        batch_op.drop_column('normalized_order_id')

    with op.batch_alter_table('llm_explanations', schema=None) as batch_op:
        batch_op.alter_column('created_at',
               existing_type=sa.DATETIME(),
               nullable=True,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))

    with op.batch_alter_table('datasets', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_datasets_user_id'))
        batch_op.create_index('ix_datasets_owner', ['user_id', 'kind'], unique=False)
        batch_op.alter_column('created_at',
               existing_type=sa.DATETIME(),
               nullable=True,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))

    with op.batch_alter_table('reconciliation_runs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_reconciliation_runs_user_id'))
        batch_op.drop_index(batch_op.f('ix_reconciliation_runs_payments_dataset_id'))
        batch_op.drop_index(batch_op.f('ix_reconciliation_runs_orders_dataset_id'))

    op.drop_table('reconciliation_runs')
    with op.batch_alter_table('import_errors', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_import_errors_dataset_id'))

    op.drop_table('import_errors')
    # ### end Alembic commands ###
